services:
  backend:
    image: ghcr.io/rocklimedev/cm-accounting:latest
    restart: always

    ports:
      - "5003:3005" # Host:Container

    env_file:
      - .env

    environment:
      NODE_ENV: production
      PORT: 3005
